version: "3.2"

services:
    proxy:
        build:
            context: ./proxy/
        image: voting/proxy:1.0
        ports:
            - "8443:443"
            - "${PROXY_HTTP_PORT}:80"
        environment: 
            - VOTING_ADDR
            - RESULTS_ADDR
        logging: 
            driver: fluentd
            options: 
                tag: "proxy"
    voting:
        build:
            context: ./voting
        image: voting/voting:1.0
        env_file: .env
        environment: 
            - REDIS_PASS
            - REDIS_PORT
        logging: 
            driver: fluentd
            options: 
                tag: "voting"
    redis:
        build: 
            context: ./redis
        image: voting/redis:1.0
        environment: 
            - REDIS_PASS
            - REDIS_PORT
        logging: 
            driver: fluentd
            options: 
                tag: "redis"
    worker:
        build:
            context: ./worker
        image: voting/worker:1.0
        env_file: .env
        environment: 
            - REDIS_PASS
            - REDIS_PORT
        logging: 
            driver: fluentd
            options: 
                tag: "worker"
    mysql:
        image: mysql:8
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
            - MYSQL_DATABASE
            - MYSQL_ROOT_PASSWORD
        volumes: 
            - ./mysql:/docker-entrypoint-initdb.d
        logging: 
            driver: fluentd
            options: 
                tag: "mysql"
    results:
        build:
            context: ./results
        image: voting/results:1.0
        environment:
            - RESULTS_ADDR
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
            - MYSQL_DATABASE
        logging: 
            driver: fluentd
            options: 
                tag: "results"
    fluentd:
        image: voting/fluentd:1.0
        build: 
            context: ./fluentd
        ports:
            - "24224:24224"
            - "24224:24224/udp"
        volumes: 
            - fluentd-logs:/fluentd/log
        environment: 
            - FLUENTD_CONF=main.conf

volumes: 
    fluentd-logs: